$schema: https://json-schema.org/draft-07/schema
$defs:
  ApiSettings:
    properties:
      app_root_path:
        default: ''
        title: App Root Path
        type: string
      cors_allow_origin_regex:
        default: .*
        title: Cors Allow Origin Regex
        type: string
      db_url:
        examples:
        - postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
        - postgresql+asyncpg://postgres:postgres@db:5432/postgres
        title: Db Url
        type: string
      session_secret_key:
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        title: Api Key
        type: string
      mws_gpt_api_key:
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        title: MWS API KEY
        type: string
      def_json_documentation_path:
        default: "data/documentation.pdf"
        example: data/documentation.pdf
        title: definite json documentation
        type: string
      rag_index_path:
        default: "data/vector.index"
        example: data/vector.index
        title: RAG index path
        type: string
      mws_gpt_api_url:
        title: MWS API URL
        type: string
    required:
    - db_url
    - session_secret_key
    - mws_gpt_api_key
    - def_json_documentation_path
    - rag_index_path
    title: ApiSettings
    type: object
properties:
  api_settings:
    anyOf:
    - $ref: '#/$defs/ApiSettings'
    - type: 'null'
    default: null
title: Settings
type: object
