$schema: https://json-schema.org/draft-07/schema
$defs:
  ApiSettings:
    properties:
      app_root_path:
        default: ''
        title: App Root Path
        type: string
      cors_allow_origin_regex:
        default: .*
        title: Cors Allow Origin Regex
        type: string
      db_url:
        examples:
        - postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
        - postgresql+asyncpg://postgres:postgres@db:5432/postgres
        title: Db Url
        type: string
      session_secret_key:
        example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        title: Api Key
        type: string
    required:
    - db_url
    - session_secret_key
    title: ApiSettings
    type: object
properties:
  api_settings:
    anyOf:
    - $ref: '#/$defs/ApiSettings'
    - type: 'null'
    default: null
title: Settings
type: object
