$schema: https://json-schema.org/draft-07/schema
additionalProperties: false
description: Settings for the application.
properties:
  $schema:
    default: null
    title: $Schema
    type: string
  app_root_path:
    default: ''
    description: Prefix for the API path (e.g. "/api/v0")
    title: App Root Path
    type: string
  database_uri:
    default: sqlite:///data/db.sqlite
    description: SQLite database settings
    format: password
    title: Database Uri
    type: string
    writeOnly: true
  cors_allow_origin_regex:
    default: .*
    description: 'Allowed origins for CORS: from which domains requests to the API
      are allowed. Specify as a regex: `https://.*.innohassle.ru`'
    title: Cors Allow Origin Regex
    type: string
  session_secret_key:
    description: Secret key for session management
    format: password
    title: Session Secret Key
    type: string
    writeOnly: true
  files_dir:
    default: data/files
    description: Path to the directory where files will be stored
    format: path
    title: Files Dir
    type: string
  bot_token:
    description: Telegram bot token, get it from @BotFather
    format: password
    title: Bot Token
    type: string
    writeOnly: true
  bot_username:
    description: Telegram bot username
    title: Bot Username
    type: string
  superadmin_telegram_id:
    description: Telegram ID of the first superadmin
    title: Superadmin Telegram Id
    type: string
  default_patrons:
    default: []
    description: List of Telegram IDs of default patrons
    items:
      type: string
    title: Default Patrons
    type: array
required:
- session_secret_key
- bot_token
- bot_username
- superadmin_telegram_id
title: Settings
type: object
