"""renamed content to message

Revision ID: 567f4c31f80b
Revises: 7ea573ee34ec
Create Date: 2025-04-20 14:22:34.306410

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "567f4c31f80b"
down_revision: str | None = "7ea573ee34ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("message", sa.String(), nullable=False))
    op.drop_column("message", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("message", "message")
    # ### end Alembic commands ###
