"""set ondelete for reply_to field

Revision ID: 3a9e9fa4b75d
Revises: 28cba249bf24
Create Date: 2025-04-19 09:22:56.218383

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a9e9fa4b75d"
down_revision: str | None = "28cba249bf24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("message_reply_to_fkey", "message", type_="foreignkey")
    op.create_foreign_key(None, "message", "message", ["reply_to"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key("message_reply_to_fkey", "message", "message", ["reply_to"], ["id"])
    # ### end Alembic commands ###
