"""add reference between request and answer

Revision ID: 70cce2a57bef
Revises: 02e3a460062c
Create Date: 2025-04-19 01:53:47.243288

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70cce2a57bef"
down_revision: str | None = "02e3a460062c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("reply_to", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "message", "message", ["reply_to"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.drop_column("message", "reply_to")
    # ### end Alembic commands ###
