"""fix relations between massage and dialog

Revision ID: 7ea573ee34ec
Revises: b7becea29414
Create Date: 2025-04-19 18:54:31.896001

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ea573ee34ec"
down_revision: str | None = "b7becea29414"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "message", "dialog", ["dialog_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    # ### end Alembic commands ###
