"""make model nullable

Revision ID: 11761d5fa7bb
Revises: 6efde4142b75
Create Date: 2025-04-19 16:06:26.108127

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11761d5fa7bb"
down_revision: str | None = "6efde4142b75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message", "model", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message", "model", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
