"""add model field

Revision ID: 6efde4142b75
Revises: 3a9e9fa4b75d
Create Date: 2025-04-19 15:49:32.477322

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6efde4142b75"
down_revision: str | None = "3a9e9fa4b75d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("model", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "model")
    # ### end Alembic commands ###
