"""add dialog model

Revision ID: b7becea29414
Revises: 11761d5fa7bb
Create Date: 2025-04-19 18:33:36.650576

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7becea29414"
down_revision: str | None = "11761d5fa7bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("dialog", sa.Column("id", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dialog")
    # ### end Alembic commands ###
